export const ACCEPT_PLAYER_INVITE = "ACCEPT_PLAYER_INVITE";
export const DISCONNECTED_PLAYER = "DISCONNECT_PLAYER";
export const INVITE_PLAYER = "INVITE_PLAYER";
export const REGISTER_PLAYER = "REGISTER_PLAYER";
export const REJECT_PLAYER_INVITE = "REJECT_PLAYER_INVITE";
export const UPDATE_PLAYER = "UPDATE_PLAYER";
export const UPDATE_PLAYERS = "UPDATE_PLAYERS";

export const END_GAME = "END_GAME";
export const REGISTER_GAME = "REGISTER_GAME";
export const START_GAME = "START_GAME";
export const UPDATE_GAME_STATE = "UPDATE_GAME_STATE";

export const CANVAS_HEIGHT = 600;
export const CANVAS_WIDTH = 800;
